export default {
  validationEmpty: "",
  validationEmail: "Please enter Email Address",
  validationPassword: "Please enter Password",
  validationValidEmail: "Please enter valid Email Address",
  validationValidPassword: "Please enter valid Password",
  validationNewPassword: "Please enter New Password",
  validationValidNewPassword: "Please enter valid New Password",
  validationConfirmPassword: "Please enter Confirm Password",
  validationValidConfirmPassword: "Please enter valid Confirm Password",
  validationNewPassConfirmPassNotMatch:
    "New Password and Confirm Password does not match",
  validationVerificationCode: "Please enter Verification code",
  validationValidVerificationCode: "Please enter Valid OTP",
  validationName: "Please enter Name",
  validationValidName: "Please enter valid Name",
  validationCity: "Please enter City",
  validationValidCity: "Please enter valid City",
  validationAddress: "Please enter Address",
  validationValidAddress: "Please enter valid Address",
  validationPostalCode: "Please enter PostalCode",
  validationValidPostalCode: "Please enter valid PostalCode",
  validationEmailId: "Please enter Name",
  validationValidEmailId: "Please enter valid Name",
  validationContactDetails: "Please enter Contact Details",
  validationValidContacDetails: "Please enter valid Contact Details",
  validationNotes: "Please enter Notes",
  validationValidNotes: "Please enter valid Notes",
  validationSelectImage: "Please select User Image",
  validationDateOfBirth: "Please select Date of Birth",
  validationValidDateOfBirth: "Please select valid Date of Birth",
  validationType: "Please select Type",
  validationNotesSubmit: "Please enter description for notes!",
  validationValidNotesSubmit: "Please enter valid description for notes!",
  validationDiscount: "Please enter Discount",
  validationValidDiscount: "Please enter valid Discount",
};
